import { Question } from "../Question";
import style from "./styles.module.scss";

export function LeaderForm({ scores, setScores, leaderForm }) {
  return (
    <>
      <div className={style.container}>
        <h2>Indicadores de Desempenho</h2>
        <Question
          title={leaderForm[0].title}
          text={leaderForm[0].text}
          indice="engajamentoOrganizacional"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[1].title}
          text={leaderForm[1].text}
          indice="orientacaoResultados"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[2].title}
          text={leaderForm[2].text}
          indice="SolucaoProblemas"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[3].title}
          text={leaderForm[3].text}
          indice="Organizacao"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[4].title}
          text={leaderForm[4].text}
          indice="QualidadeProdutividade"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[5].title}
          text={leaderForm[5].text}
          indice="habilidadeTecnica"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[6].title}
          text={leaderForm[6].text}
          indice="energiaDisposicao"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[7].title}
          text={leaderForm[7].text}
          indice="TrabalhoEquipe"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[8].title}
          text={leaderForm[8].text}
          indice="atualizacao"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[9].title}
          text={leaderForm[9].text}
          indice="orientacaoCliente"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[10].title}
          text={leaderForm[10].text}
          indice="flexibilidade"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[11].title}
          text={leaderForm[11].text}
          indice="relacionamentoInterpessoal"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[12].title}
          text={leaderForm[12].text}
          indice="condicoesTrabalho"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[13].title}
          text={leaderForm[13].text}
          indice="comunicacao"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[14].title}
          text={leaderForm[14].text}
          indice="conflitos"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[15].title}
          text={leaderForm[15].text}
          indice="tomadaDecisoes"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[16].title}
          text={leaderForm[16].text}
          indice="criatividade"
          value={scores}
          onSetValue={setScores}
        />
        <Question
          title={leaderForm[17].title}
          text={leaderForm[17].text}
          indice="lideranca"
          value={scores}
          onSetValue={setScores}
        />
      </div>
    </>
  )
}